/** Uncrossable Rush – side camera edition. Chicken advances LEFT -> RIGHT. */
class Game {
 constructor(){
  this.canvas=document.getElementById('gameCanvas'); this.ctx=this.canvas.getContext('2d');
  this.width=720; this.height=980; this.totalLanes=24; this.laneWidth=92; this.roadTotalWidth=(this.totalLanes+2)*this.laneWidth;
  this.setupCanvas(); this.state='IDLE'; this.currentLane=0; this.difficulty='medium'; this.cameraX=0; this.targetCameraX=0; this.screenShake=0;this.redFlash=0;this.coinParticles=[];this.barriers={};this.lastTime=performance.now();
  this.initMultipliers();
  const sx=this.getLaneCenterX(0), sy=this.height*.60; this.chicken=new Chicken(sx,sy,this.laneWidth);
  this.traffic=new TrafficManager(this.height,this.laneWidth,this.totalLanes);this.traffic.setDifficulty(this.difficulty);this.traffic.populateInitial(this.height,this.barriers);
  window.addEventListener('resize',()=>this.setupCanvas());requestAnimationFrame(t=>this.loop(t));
 }
 setupCanvas(){const dpr=Math.min(window.devicePixelRatio||1,2);this.width=720;this.height=980;this.canvas.width=this.width*dpr;this.canvas.height=this.height*dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);}
 initMultipliers(){this.multipliers={easy:[1.12,1.25,1.40,1.58,1.80,2.05,2.35,2.75,3.25,3.85,4.60,5.55,6.75,8.30,10.3,13,16.5,21.5,28.5,38.5,53,75,110,180],medium:[1.35,1.62,1.98,2.45,3.10,4,5.25,7,9.5,13.2,18.5,26.5,38.5,57,86,132,208,335,550,920,1600,2900,5400,10000],hard:[1.75,2.35,3.2,4.5,6.4,9.3,13.8,21,32.5,52,85,142,245,430,780,1450,2800,5600,11500,24000,52000,115000,260000,600000],hardcore:[2.5,4.1,6.9,12,21.5,39,74,145,290,600,1280,2800,6200,14200,33500,82000,205000,530000,1400000,3800000,10000000,28000000,80000000,250000000]};}
 setDifficulty(d){if(this.state==='PLAYING'||this.state==='HOPPING')return;this.difficulty=d;this.traffic.setDifficulty(d);if(window.uiController)window.uiController.updateMultiplierLadder();}
 getCurrentMultiplier(){if(this.currentLane<=0)return 1;const a=this.multipliers[this.difficulty];return a[Math.min(this.currentLane-1,a.length-1)];}
 getNextMultiplier(){const a=this.multipliers[this.difficulty];return a[Math.min(this.currentLane,a.length-1)];}
 getLaneCenterX(i){return (i+.5)*this.laneWidth;}
 startRound(){if(this.state==='PLAYING'||this.state==='HOPPING')return;this.currentLane=0;this.coinParticles=[];this.barriers={};this.state='PLAYING';this.chicken.reset(this.getLaneCenterX(0),this.height*.60);this.cameraX=0;this.targetCameraX=0;if(window.soundEngine&&!window.soundEngine.isPlayingMusic)window.soundEngine.startMusic();if(window.uiController)window.uiController.onRoundStarted();}
 stepForward(){if(this.state!=='PLAYING'&&this.state!=='IDLE')return;if(this.state==='IDLE'&&window.uiController&&!window.uiController.placeBet())return;if(this.currentLane>=this.totalLanes)return;this.state='HOPPING';this.chicken.hopToX(this.getLaneCenterX(this.currentLane+1));if(window.uiController)window.uiController.updateButtons();}
 onLanding(l){this.currentLane=l;if(this.currentLane>=this.totalLanes){this.state='VICTORY';this.spawnCoinCelebration(this.chicken.x,this.chicken.y);if(window.soundEngine)window.soundEngine.playCashOut();if(window.uiController)window.uiController.onVictory();}else{this.state='PLAYING';if(window.uiController)window.uiController.onSafeLanding();}}
 cashOut(){if(!this.currentLane||this.state!=='PLAYING')return;this.state='CASHED_OUT';const m=this.getCurrentMultiplier();this.spawnCoinCelebration(this.chicken.x,this.chicken.y);if(window.soundEngine)window.soundEngine.playCashOut();if(window.uiController)window.uiController.onCashOut(m);}
 crash(car){if(this.state==='CRASHED')return;this.state='CRASHED';this.screenShake=15;this.redFlash=.55;this.chicken.die(80);if(window.soundEngine){window.soundEngine.playCrashImpact();window.soundEngine.playTireScreech();}if(window.uiController)window.uiController.onCrash();}
 triggerShake(a){this.screenShake=Math.max(this.screenShake,a);}
 spawnCoinCelebration(x,y){for(let i=0;i<32;i++){const a=Math.random()*Math.PI*2,s=120+Math.random()*230;this.coinParticles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-80,radius:5+Math.random()*4,alpha:1,life:1.2+Math.random()*.7});}}
 loop(t){const dt=Math.min((t-this.lastTime)/1000,.05);this.lastTime=t;this.update(dt);this.draw();requestAnimationFrame(n=>this.loop(n));}
 update(dt){this.chicken.update(dt);if(this.state==='HOPPING'&&!this.chicken.isJumping&&!this.chicken.isDead)this.onLanding(this.currentLane+1);this.traffic.update(dt,this.height,this.barriers,this.chicken);if((this.state==='PLAYING'||this.state==='HOPPING')&&!this.chicken.isDead){const hit=this.traffic.checkCollision(this.chicken);if(hit)this.crash(hit);}for(let i=this.coinParticles.length-1;i>=0;i--){const p=this.coinParticles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=320*dt;p.life-=dt;p.alpha=Math.max(0,p.life);if(p.life<=0)this.coinParticles.splice(i,1);}this.screenShake=Math.max(0,this.screenShake-35*dt);this.redFlash=Math.max(0,this.redFlash-1.8*dt);const lookAhead=this.chicken.x-this.width*.28;this.targetCameraX=Math.max(0,Math.min(this.roadTotalWidth-this.width,lookAhead));this.cameraX+=(this.targetCameraX-this.cameraX)*7*dt;}
 draw(){const c=this.ctx;c.save();c.fillStyle='#070b15';c.fillRect(0,0,this.width,this.height);if(this.screenShake){c.translate((Math.random()*2-1)*this.screenShake,(Math.random()*2-1)*this.screenShake);}c.save();c.translate(-this.cameraX,0);this.drawCity(c);this.drawRoad(c);this.traffic.draw(c);this.chicken.draw(c);for(const p of this.coinParticles){c.save();c.globalAlpha=p.alpha;c.fillStyle='#ffd700';c.beginPath();c.arc(p.x,p.y,p.radius,0,Math.PI*2);c.fill();c.restore();}c.restore();if(this.redFlash){c.fillStyle=`rgba(255,23,68,${this.redFlash})`;c.fillRect(0,0,this.width,this.height);}c.restore();}
 drawCity(c){const x=this.cameraX;c.fillStyle='#0c1730';c.fillRect(x,0,this.width,190);for(let i=0;i<14;i++){const bx=x+i*70-20,h=80+(i%4)*20;c.fillStyle=i%2?'#111d39':'#0e1830';c.fillRect(bx,190-h,58,h);c.fillStyle='rgba(255,193,7,.6)';for(let wy=125-h;wy<175;wy+=22)for(let wx=bx+10;wx<bx+50;wx+=19)if((wx+wy+i)%3<1.4)c.fillRect(wx,wy,7,10);}const g=c.createLinearGradient(0,150,0,220);g.addColorStop(0,'#162042');g.addColorStop(1,'#09111f');c.fillStyle=g;c.fillRect(x,185,this.width,80);}
 drawRoad(c){const top=225,bottom=this.height-80,h=bottom-top;c.fillStyle='#121824';c.fillRect(0,top,this.roadTotalWidth,h);for(let i=0;i<=this.totalLanes+1;i++){const lx=i*this.laneWidth;c.fillStyle=(i%2)?'#151e2b':'#101722';c.fillRect(lx,top,this.laneWidth,h);if(i>0&&i<=this.totalLanes){c.fillStyle='rgba(255,255,255,.30)';for(let y=top+15;y<bottom;y+=46)c.fillRect(lx-1,y,2,24);this.drawMultiplier(c,i,lx+this.laneWidth*.5,top+46);} }
  c.fillStyle='#242e3c';c.fillRect(0,top-10,this.roadTotalWidth,10);c.fillRect(0,bottom,this.roadTotalWidth,20);c.fillStyle='#ff5252';for(let x=0;x<this.roadTotalWidth;x+=52){c.fillRect(x,top-10,26,10);c.fillRect(x,bottom,26,20);}c.fillStyle='#263238';c.fillRect(0,top,this.laneWidth,h);c.fillStyle='#2e7d32';c.fillRect(0,bottom-55,this.laneWidth,55);
 }
 drawMultiplier(c,i,x,y){const m=this.multipliers[this.difficulty][i-1]||1,passed=i<=this.currentLane,next=i===this.currentLane+1;c.save();c.translate(x,y);c.fillStyle=passed?'rgba(0,230,118,.25)':next?'rgba(0,229,255,.28)':'rgba(7,14,27,.72)';c.strokeStyle=passed?'#00e676':next?'#00e5ff':'#334155';c.lineWidth=1.5;c.beginPath();c.roundRect(-32,-17,64,34,16);c.fill();c.stroke();c.fillStyle=passed?'#00e676':next?'#00e5ff':'#d7e0ea';c.font='bold 14px monospace';c.textAlign='center';c.textBaseline='middle';c.fillText(m.toFixed(2)+'x',0,0);c.restore();}
}
window.gameInstance=null;
